### ISSUE TITLE
Split up BexioApi.cs into partial classes   

### ISSUE THREAD

**Issue by ninomllr** [substringgmbh/bexio.net#2]
I propose to split up the class `BexioApi.cs` into multiple partial classes based on data types to make it more maintainable.

**Comment by ninomllr** [comment]
@ntold and @genyx what do you think about this?

**Comment by delasource** [comment]
I agree. I used this approach in another API project. I could easily adapt it

**Comment by ninomllr** [comment]
I discussed this change briefly with @ntold today. He would have time to do it as well, we just wanted to quickly check in with you to coordinate efforts. Would you have time today or tomorrow to do this @ntold?

**Comment by delasource** [comment]
Check this
https://github.com/genyx/DomrobotDotNet/blob/main/InwxDomrobot/DomrobotApi.cs#L63
https://github.com/genyx/DomrobotDotNet/blob/main/InwxDomrobot/Apis/AccountApi.cs

**Comment by ntold** [comment]
Sure thing @ninomllr, it'll be done by tomorrow. I'll split in up in partial classes based on data types

**Comment by delasource** [comment]
It's ok. 

The usage of the api is not simplified by this approach though. For that i have used this pattern before (as linked above):

```csharp
var _bexioApi = new BexioApi("token");

var allUsers = await _bexioApi.Users.GetAllAsync();
var singleUser = await _bexioApi.Users.GetAsync(17);

var projectOne = await _bexioApi.Projects.GetAsync(1);
var milestones = await _bexioApi.Projects.GetMilestonesAsync(projectOne);
// or
    milestones = await _bexioApi.Projects.Milestones.GetAllAsync(projectOne);
// ...
```

(so i created (internal) classes that are made public properties of the main BexioApi class)



Another thought by the way: "Get" APIs (to get a single item) should be called "Fetch" or "FetchSingle" as it is called so in the official docs.

Opinions?

**Comment by ntold** [comment]
Good point there, fair enough! 

What about if we combine these two approaches. 
Instead of making one big bexioApi-class we split in subclasses, as you mentioned, and create partial classes on each Endpoint (in your example  `_bexioApi.Projects`).

`_bexioApi.Projects` would be the subclass and have partial classes for `BusinessActivities`, `Timesheet`, and so on...

**Comment by delasource** [comment]
I personally only use partial classes for splitting different behaviour (ex: Model/Controller), not for cleaner code.

Sure you want to have smaller files. I have no problem with your combined approach. Its just not my personal style 😅
