### ISSUE TITLE
Properly implement HTTP 503 error

### ISSUE THREAD

**Issue by delasource** [substringgmbh/bexio.net#4]
Problem:

Response Status Code 503 does not indicate a faulty request but that the api server is currently not available. From documentation: `503 | The server is not available (maintenance work)`

Approach 1: The user needs to get a result that indicates that the server is (currently) not available. (can be done right now, when throw-style is used via constructor)

Approach 2: The failed request should be reexecuted some time later. If that fails again, then the user gets to see the error.

**Comment by ninomllr** [comment]
Basically I believe we should forward the error directly (meaning approach 1) and not take care of error handling / resume-on-error behaviour in the wrapper. IMO this should be handled by the application using bexio.net.

So I would vote for Approach 1
